import { TodoResponse } from "@/types/todo";

import { GOAL_MOCK_DATA } from "../goals/mock-data";

export const TODO_MOCK_DATA: TodoResponse[] = [
  {
    id: 1,
    noteId: null,
    title: "자바스크립트 1강 끝내기",
    goalInformation: null,
    linkUrl: null,
    fileUrl: null,
    isDone: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    noteId: null,
    title: "리렌더링 성능 최적화 실습",
    goalInformation: {
      id: GOAL_MOCK_DATA[0].id,
      title: GOAL_MOCK_DATA[0].title,
    },
    linkUrl: null,
    fileUrl: null,
    isDone: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 3,
    noteId: null,
    title: "리액트 Fiber 이해하기",
    goalInformation: {
      id: GOAL_MOCK_DATA[0].id,
      title: GOAL_MOCK_DATA[0].title,
    },
    linkUrl: null,
    fileUrl: null,
    isDone: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 4,
    noteId: null,
    title: "Next.js 공식문서 읽기",
    goalInformation: {
      id: GOAL_MOCK_DATA[1].id,
      title: GOAL_MOCK_DATA[1].title,
    },
    linkUrl: null,
    fileUrl: null,
    isDone: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 5,
    noteId: null,
    title: "알고리즘 문제 풀기 - 1일차",
    goalInformation: {
      id: GOAL_MOCK_DATA[2].id,
      title: GOAL_MOCK_DATA[2].title,
    },
    linkUrl: null,
    fileUrl: null,
    isDone: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 6,
    noteId: null,
    title: "알고리즘 문제 풀기 - 2일차",
    goalInformation: {
      id: GOAL_MOCK_DATA[2].id,
      title: GOAL_MOCK_DATA[2].title,
    },
    linkUrl: null,
    fileUrl: null,
    isDone: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 7,
    noteId: null,
    title: "알고리즘 문제 풀기 - 3일차",
    goalInformation: {
      id: GOAL_MOCK_DATA[2].id,
      title: GOAL_MOCK_DATA[2].title,
    },
    linkUrl: null,
    fileUrl: null,
    isDone: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 8,
    noteId: null,
    title: "알고리즘 문제 풀기 - 4일차",
    goalInformation: {
      id: GOAL_MOCK_DATA[2].id,
      title: GOAL_MOCK_DATA[2].title,
    },
    linkUrl: null,
    fileUrl: null,
    isDone: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 9,
    noteId: null,
    title: "알고리즘 문제 풀기 - 5일차",
    goalInformation: {
      id: GOAL_MOCK_DATA[2].id,
      title: GOAL_MOCK_DATA[2].title,
    },
    linkUrl: null,
    fileUrl: null,
    isDone: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
